### ISSUE TITLE
开源项目 fork 计划回复报名

### ISSUE THREAD

**Issue by haobug** [cdlug/cdlug.github.io#12]
回复本条 issue，拉你进 cdlug 的组织. [Fork] 喜欢的开源项目到 cdlug 组织id 下。

提交代码贡献太难，
那，点下 `[Fork]` 或 `[Star]` 是不是 so easy 啦。
> btw，回复本条也可以刷绿。

目标是收集大家关注的开源项目，然后抱团，互相交流，完成心愿，
即使去捐款也能更容易 cover 住银行的手续费不是？

再然后呢?
> 嘿嘿嘿。

**Comment by windkoo** [comment]
你怎么可以这样水。

**Comment by sinoyster** [comment]
sinoyster这个组织都荒了很久了

**Comment by haobug** [comment]
@sinoyster 邀请你了。

**Comment by ghost** [comment]
cdlug还有活人吗。。。

**Comment by haobug** [comment]
@infurth 我算半个

**Comment by ghost** [comment]
@haobug 现在还有什么活动阵地值得加入吗

**Comment by BedrockDigger** [comment]
Halo

**Comment by BedrockDigger** [comment]
呃... @haobug 这里没人了么。。。🙄

**Comment by haobug** [comment]
@BedrockDigger  有。

**Comment by BedrockDigger** [comment]
> @BedrockDigger 有。

非常感谢🙃

**Comment by QuantumGhost** [comment]
2333 这个延迟好高

**Comment by haobug** [comment]
修改为有贡献加入
