### ISSUE TITLE
决定 CDLUG 文档的开源协议，添加社区准则

### ISSUE THREAD

**Issue by QuantumGhost** [cdlug/cdlug.github.io#30]
#20 这里，如果想要免费使用 Netlify 的组织的话，需要填一个 [开源组织申请](https://opensource-form.netlify.com/)，里面有几个需要确定的点

1. 代码的授权协议
2. 一份 [社区准则（Code of Conduct）](https://en.wikipedia.org/wiki/Code_of_conduct)

1 的话，至少这个仓库应该主要以文档为主，可以考虑 [CC 授权](https://creativecommons.org/choose/) 里面选一个合适的。我个人建议使用 [署名-相同方式共享 4.0 国际 (CC BY-SA 4.0) ](https://creativecommons.org/licenses/by-sa/4.0/deed.zh)。

另外，我们应该要求**所有**贡献给 CDLUG 的内容都必须使用 1 中选择的协议，或者使用与 1 中选择的协议相兼容的协议。

2 的话，我觉得需要去参考一下其他开源组织的，下面的可以供参考：

- [CNCF](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)
- [Apache](https://www.apache.org/foundation/policies/conduct)
- [Linux 基金会](https://events.linuxfoundation.org/code-of-conduct/)

我个人建议使用简短的社区准则

**Comment by QuantumGhost** [comment]
CNCF 那个我感觉不错，而且也有中英双语，改改就能直接用了

**Comment by haobug** [comment]
这个 cc by sa license 页面，标题写着，百度云加速看着有点惊悚。
其他都还好。

**Comment by QuantumGhost** [comment]
CF 国内版吧，其他应该不影响

**Comment by QuantumGhost** [comment]
Resolved in #35
