### ISSUE TITLE
Hugo post guide

### ISSUE THREAD

**Issue by haobug** [cdlug/cdlug.github.io#34]

**Comment by QuantumGhost** [comment]
其实 hugo 命令行就有 new 子命令，`hugo new content/post/xxx.md` 就能简单地新建一篇了

所以说 post guide 感觉主要说一下在 Github 上建 post 就好了

**Comment by haobug** [comment]
> 其实 hugo 命令行就有 new 子命令，`hugo new content/post/xxx.md` 就能简单地新建一篇了
> 

感觉被上当的感觉。不过算是有理由学一下 go 了。
这个我还是会选择在线编辑器编辑，所以需要 hugo 的在线编辑链接。

> 所以说 post guide 感觉主要说一下在 Github 上建 post 就好了

* 这个不只是文件，除了文件创建，还有比如 tags 需要怎么写(guide 文章其实就是个示例)
* 比如新建了文件需要过哪些检查，怎么触发重新生成？

**Comment by QuantumGhost** [comment]
> 这个不只是文件，除了文件创建，还有比如 tags 需要怎么写(guide 文章其实就是个示例)

可以给个模板（其实从命令行新建是有模板的）

> 比如新建了文件需要过哪些检查，怎么触发重新生成？

检查？没懂

触发重新生成不需要贡献者关心

**Comment by too** [comment]
对于在线编辑器或者发布的后台，可以看看 [Git-backed CMS for Gatsby, Gridsome, Eleventy, Hugo, VuePress, Jekyll, etc. | Forestry.io](https://forestry.io/)，可能直接可以用
