### ISSUE TITLE
hugo -D  server --bind 0.0.0.0 显示空白网页

### ISSUE THREAD

**Issue by haobug** [cdlug/cdlug.github.io#40]
Q: hugo -D  server --bind 0.0.0.0 显示空白网页

A: 主题 submodule 也要下载，才能正常预览

```
git submodule init
git submodule update
```

**Comment by too** [comment]
所以这个我会放在 Hugo Guide 里？ Not an Issue？

**Comment by QuantumGhost** [comment]
放 Readme.md 里面吧

**Comment by too** [comment]
我在 README 里提示查看 Hugo Guide？

**Comment by QuantumGhost** [comment]
贡献指南其实直接写 readme 里面（或者在 README 里面放一个链接到真实的文档）比较好，这样一打开 Repo 就能看到

**Comment by haobug** [comment]
> 所以这个我会放在 Hugo Guide 里？ Not an Issue？

这个可以关闭了，我看到 guide 里面已经包括了。


> 贡献指南其实直接写 readme 里面（或者在 README 里面放一个链接到真实的文档）比较好，这样一打开 Repo 就能看到

赞同，直接把 hugo guide 那篇 synlink 到 README ，不过这本来是偷懒做法。
而 @too 现在你已经写了两份了[摊手]，当然是两份都要要。

**Comment by too** [comment]
两份的作用不同嘛～ 那楼主自己关闭哦
